name: Trigger Render Deploy

on:
  push:
    branches:
      - main  # or 'master' based on your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Render Deploy Hook
        run: curl -X POST https://api.render.com/deploy/srv-d0ee5t3uibrs73bif7mg?key=uBluh6CA5-A
